### ISSUE TITLE
Images are distorted in blog posts

### ISSUE THREAD

**Issue by k01255322** [ICT4Dat/legacy-ict4dat-website#10]
![distortedImage](https://user-images.githubusercontent.com/34097219/111670128-c96e3380-8817-11eb-9c95-b78c21a04325.png)

Some images in our blog posts are distorted because only a max-width but no height is set. Adding height:auto should solve the issue. 

Probably this post (https://wordpress.org/support/topic/images-now-stretched-and-distorted-after-5-5-upgrade/) will help.

**Comment by spipau** [comment]
Possible fix proposed by @k01255322 is to add `height: auto;`

```
.wp-block-image img {
    max-width: 100%;
    height: auto;
}
```
